description: Desenvolva e publique a sua CLI personalizada ou APIs Lambda com a Stack de Phyton.
name: stackspot-python-stack
display-name: Python Stack
picture: https://hotmart.s3.amazonaws.com/product_contents/a3145272-0002-459b-a71b-08563972ec7e/640pxPythonlogonotextsvg.png
category: Backend # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility: # Put a list of technologies compatible with the stack
  - Python
technologies: # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologies
  - Python
about: docs/about.md
use-cases:
  - title: Criar uma CLI personalizada em Python 
    content: docs/use-case-cli.md
    stackfile: stackfiles/create_cli.yaml
  - title: Criar uma API Lambda em Python 
    content: docs/use-case-api.md
    stackfile: stackfiles/create_api.yaml
