name: Publish

on:
  push:
    branches:
      - test/publish-pipe
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: Download STK
        run: curl -O https://stk-dev.stackspot.com/installer-pre-release/linux/stk-alpha.deb

      - name: Install STK and create/move env
        env:
          STK_ENV: ${{ secrets.STK_ENV }}
        run: |
          sudo dpkg --install stk-alpha.deb
          echo $STK_ENV > $HOME/.stk-alpha/.env
          mv $HOME/.stk-alpha/bin/* /usr/local/bin

      - name: Login to StackSpot Account
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_KEY: ${{ secrets.CLIENT_KEY }}
          REALM: ${{ secrets.REALM }}
        run: stk-alpha login --client-id $CLIENT_ID --client-key $CLIENT_KEY --realm $REALM

      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish to the registry
        env:
          REGISTRY_BASE_URL: https://registry.stackspot.com
        run: |
          echo $REGISTRY_BASE_URL
          stk-alpha publish stack

      - name: Show Log
        if: always()
        run: |
          cd $HOME/.stk-alpha/logs/
          cat logs.log
